on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

name: texor-convert-win
jobs:
  convert:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
      - name: pandoc setup
        uses: r-lib/actions/setup-pandoc@v2
      - name: Pre Install
        run: |
          curl -o DESCRIPTION https://raw.githubusercontent.com/Abhi-1U/texor/master/DESCRIPTION
        shell: bash
        working-directory: '.'
      - name: install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: Post Install
        run: |
          rm DESCRIPTION
        working-directory: "."
        shell: bash
      - name: install texor
        run: |
          pak::pkg_install("Abhi-1U/texor")
        shell: Rscript {0}
        working-directory: '.'
      - name: Convert
        run: |
          texor::latex_to_web('.')
        shell: Rscript {0}
        working-directory: '.'
      - name: Upload folder
        uses: actions/upload-artifact@v3
        with:
          name: RJwrapper.html
          path: RJwrapper.html
          