on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

name: texor-convert-win
jobs:
  convert:
    strategy:
      fail-fast: false
      matrix:
        pandoc_version: ['3.1.2', '2.18', '2.17', '2.16.2', '2.15', '2.14.2', '2.13']
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      - name: pandoc setup
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: ${{ matrix.pandoc_version }}
      - name: install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: install texor
        run: |
          pak::pkg_install("Abhi-1U/texor")
        shell: Rscript {0}
        working-directory: '.'
      - name: Convert
        run: |
          texor::latex_to_web('.')
        shell: Rscript {0}
        working-directory: '.'
      - name: zip the folder
        run: |
          ##----------------
          zip -r web.zip web
        shell: bash
        working-directory: '.'
      - name: Upload folder
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: web.zip
          