on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

name: texor-convert
jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      - name: pandoc setup
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      - name: curl headers
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
        shell: bash 
      - name: lib poppler
        run: |
          sudo apt-get install -y libpoppler-cpp-dev
        shell: bash
      - name: install texor
        run: |
          ## --------------------------------------------------------------------
          install.packages("rmarkdown",version='2.20')
          install.packages(c("pdftools","tinytex","xfun","logger","stringr","yaml","pak","rjtools"))
          pak::pkg_install("Abhi-1U/rebib")
          pak::pkg_install("Abhi-1U/texor@sample-paper")
        shell: Rscript {0}
        working-directory: '.'
      - name: convert
        run: |
          texor::latex_to_web(dir)
        shell: Rscript {0}
        working-directory: '.'
      - name: zip the folder
        run: |
          ##----------------
          zip -r web.zip web
        shell: bash
        working-directory: '.'
      - name: Upload folder
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: web.zip
          