on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

name: texor-convert
jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install cURL Headers
        run: curl http://ftp.us.debian.org/debian/pool/main/c/curl/libcurl4-openssl-dev_7.88.1-8_amd64.deb | sudo dpkg -i libcurl4-openssl-dev_7.88.1-8_amd64.deb
        shell: bash     
      - name: setup
        uses: r-lib/actions/setup-r@v2
      - name: convert
        run: |
          ## --------------------------------------------------------------------
          install.packages(c("rmarkdown", "pdftools","tinytex","xfun","logger","stringr","yaml","remotes"))
          remotes::install_github("Abhi-1U/rebib")
          remotes::install_github("Abhi-1U/texor@sample-paper")
          texor::latex_to_web(".")
        shell: Rscript {0}
        working-directory: '.'
      - name: zip the folder
        run: |
          ##-
          zip -r web.zip web
        shell: bash
        working-directory: '.'
      - name: Upload folder
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: web.zip
          