# Test workflow script
on:
  push:
    branches: [main, master]
  pull_request:
  	branches: [main, master]
inputs:
	working-directory:
    	description: 'Working Directory file path'
		default: '.'
name: texor-convert

jobs:
	convert:
		runs-on: ubuntu-latest
		env:
    	    GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
		steps:
    		- name: convert the article
				uses: r-lib/actions/setup-r@v2
				run: |
                    ## --------------------------------------------------------------------
                    Rscript -e 'install.packages(c("rmarkdown", "pdftools","tinytex","xfun","logger","stringr","yaml","remotes"))'
                    Rscript -e 'remotes::install_github("Abhi-1U/rebib")'
                    Rscript -e 'remotes::install_github("Abhi-1U/texor@sample-paper")'
                    Rscript -e 'texor::latex_to_web(".")'
                    zip -r web.zip web
				shell: bash
				working-directory: ${{ inputs.working-directory }}
			- name: Upload web folder
				uses: actions/upload-artifact@v3
                with:
                    name: web
                    path: web.zip
