on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

name: texor-convert
jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      - name: pandoc setup
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      - name: curl headers
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
        shell: bash 
      - name: lib poppler
        run: |
          sudo apt-get install -y libpoppler-cpp-dev
        shell: bash
      - name: Pre Install
        run: |
          FILE="DESCRIPTION"
          if [ -f $FILE ]; then
            echo "DESCRIPTION File exists, moving temporarily"
            mkdir desc_temp
            mv $FILE desc_temp
            curl -o DESCRIPTION https://raw.githubusercontent.com/Abhi-1U/texor/master/DESCRIPTION
          else 
            echo "DESCRIPTION File does not exist"
            curl -o DESCRIPTION https://raw.githubusercontent.com/Abhi-1U/texor/master/DESCRIPTION
          fi
        shell: bash
        working-directory: '.'
      - name: install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: install texor
        run: |
          pak::pkg_install("rjournal/rjtools")
          pak::pkg_install("Abhi-1U/rebib")
          pak::pkg_install("Abhi-1U/texor@sample-paper")
          texor::latex_to_web('.')
        shell: Rscript {0}
        working-directory: '.'
      - name: Post Install
        run: |
          FILE="DESCRIPTION"
          OGDF="desc_temp/DESCRIPTION"
          if [ -f $OGDF ]; then
            echo "Restoring DESCRIPTION File"
            rm $FILE
            mv $OGDF ./DESCRIPTION
            rm -rf desc_temp
          else
            echo "Deleting DESCRIPTION FILE"
            rm $FILE
          fi
        working-directory: "."
        shell: bash
      - name: Convert
        run: |
          texor::latex_to_web('.')
        shell: Rscript {0}
        working-directory: '.'
      - name: zip the folder
        run: |
          ##----------------
          zip -r web.zip web
        shell: bash
        working-directory: '.'
      - name: Upload folder
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: web.zip
          